# Some Secrets
secret:
  session: session-secret
  cookie: cookie-secret

# postgres connection options
postgres:
  uri: postgres://postgres:@192.168.99.100:5432/blog

# Redis connection options
redis:
  uri: redis://192.168.99.100:6379

# Should we populate the DB with sample data?
seedDb: true
